version: '3'

services:
  php-apache:
    build: .
    ports:
      - "8080:80"
    networks:
      - my-network
  mysql:
    image: mysql:latest
    env_file: .mysql.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my-network

volumes:
  mysql_data:

networks:
  my-network:
    driver: bridge
